# Generated by Django 5.0.3 on 2024-07-12 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isfsite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quant",
            name="firm",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="firm_quant",
                to="isfsite.firm",
            ),
        ),
    ]
