# Generated by Django 5.0.3 on 2024-07-16 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isfsite", "0003_alter_firm_currency_alter_firm_industry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firm",
            name="hq_location",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="firm_loc",
                to="isfsite.location",
            ),
        ),
    ]
