# Generated by Django 5.0.3 on 2024-07-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isfsite", "0004_alter_firm_hq_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="hasScope1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="firm",
            name="hasScope2",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="firm",
            name="hasScope3",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="firm",
            name="hasTargets",
            field=models.BooleanField(default=False),
        ),
    ]
