# Generated by Django 5.0.3 on 2024-08-13 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isfsite", "0005_firm_hasscope1_firm_hasscope2_firm_hasscope3_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CDPActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CDPIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="firm",
            name="site",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="firm",
            name="cdp_activity",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="firms",
                to="isfsite.cdpactivity",
            ),
        ),
        migrations.AddField(
            model_name="firm",
            name="cdp_industry",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="firms",
                to="isfsite.cdpindustry",
            ),
        ),
        migrations.CreateModel(
            name="CDPSector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="isfsite.cdpindustry",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cdpactivity",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="isfsite.cdpsector",
            ),
        ),
        migrations.AddField(
            model_name="firm",
            name="cdp_sector",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="firms",
                to="isfsite.cdpsector",
            ),
        ),
    ]
